### PR TITLE
Issue #341: update to Checkstyle 10.1

### LINKED ISSUE #341: upgrade to checkstyle 10.1
https://checkstyle.org/releasenotes.html#Release_10.1

### PR DESCRIPTION
**Pull request by Calixte**
Fixes #341.
Screenshot from 2022-10-31 18-51-50

### CODE REVIEW

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Thanks a lot!!

**Review by rnveach — COMMENTED** [review]
Is https://github.com/checkstyle/eclipse-cs/issues/348 not an issue preventing us from continuing to do releases?

**Comment by rnveach** [comment]
Btw, is any of this documented in https://github.com/checkstyle/eclipse-cs/wiki/How-to-release-(old)(manual) or https://github.com/checkstyle/eclipse-cs/wiki/How-to-release-(automated) so others can start learning the process and maybe check things off?

**Comment by Bananeweizen** [comment]
> Is #348 not an issue preventing us from continuing to do releases?

Well, as long as people are running on a Java 11+ and recent enough Eclipse version, it will all work. So the Java 11+ changes are not completely blocking. However, they should still be done soon to avoid people with very old Eclipse trying to upgrade and not being able to use the plugin after the upgrade.

**Comment by Bananeweizen** [comment]
Change looks good to me. 👍🏻

**Pull request merged**
