### PR TITLE
#102 Upgrade to Checkstyle 8.13

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by valfirst** [comment]
@rnveach, thank you for your comments and sorry for delay, I was very busy with work activities. PR is updated, please, review

**Comment by romani** [comment]
looks ok, "same set" of files are changed as in previous update - https://github.com/checkstyle/eclipse-cs/commit/c9d7634afbddcb1111f569230af0e86fe395306f?diff=unified

@lkoe , @Bananeweizen , please review.

**Comment by valfirst** [comment]
> BIN +10.5 MB ...ipsecs.checkstyle/checkstyle-8.12-all.jar → ...ipsecs.checkstyle/checkstyle-8.13-all.jar
> BIN +5.97 MB ...checkstyle/checkstyle-checkstyle-8.12.zip → ...checkstyle/checkstyle-checkstyle-8.13.zip

@lkoe which one old 8.12-all.jar/zip are you referring?

**Comment by lkoe** [comment]
@valfirst ah, sorry, I missed that it was already recognized as a "rename". Nevermind then, everything's good

**Pull request merged**
