### PR TITLE
Issue #420: update to Checkstyle 10.5.0

### LINKED ISSUE #420: upgrade to checkstyle 10.5.0
https://checkstyle.org/releasenotes.html#Release_10.5.0

### PR DESCRIPTION
**Pull request by Calixte**
Fixes #420.
Screenshot 2023-03-21 at 6 43 19 PM

### CODE REVIEW

**Review by rnveach — CHANGES_REQUESTED** [review]
https://github.com/checkstyle/eclipse-cs/pull/478 needs to be merged first, otherwise the artifact we create from a release will not work imo.

**Comment by Calixte** [comment]
> #478 needs to be merged first, otherwise the artifact we create from a release will not work imo.

It was unclear to me whether it applied to artifacts generated by the release as well, but @Bananeweizen seems to be saying that we should have it regardless, so I merged it.

**Comment by rnveach** [comment]
> It was unclear to me 

How did you test this before the other fix was merged? I have been testing by creating a release and installing into a new eclipse installation.

**Review by rnveach — APPROVED** [review]

**Review by romani — APPROVED** [review]
Ok to merge, no need in my review. One Reviewer is enough.

**Pull request merged**
