### PR TITLE
Issue #279: deploy to github pages instead of bintray

### PR DESCRIPTION
**Pull request by Calixte**
Followed this guide: http://www.lorenzobettini.it/2021/03/publishing-an-eclipse-p2-composite-repository-on-github-pages/
P2 GitHub Pages repository looks like: https://github.com/Calixte/eclipse-cs-update-site
Update site: https://calixte.github.io/eclipse-cs-update-site/

I've tested and it works well.
We probably want to put this repository in the checkstyle organization, and point a better domain to it.

### CODE REVIEW

**Review by romani — APPROVED** [review]
Better to use org pages, because some other can help you do release.
Let me know if you need access to some repo or ... .

**Comment by Calixte** [comment]
I don't have enough permissions to create a repo at `checkstyle/eclipse-cs-update-site`.
The update site URL would be `checkstyle.org/eclipse-cs-update-site` which is pretty nice.

**Comment by romani** [comment]
@Calixte ,
https://github.com/checkstyle/eclipse-cs-update-site is created, you have Maintainer role.
Let me know if you need anything else.

**Comment by lkoe** [comment]
Nicely done to get it working again.
A small point: you could have just updated the URLs in `docs/update/compositeArtifacts.xml ` and `docs/update/compositeContent.xml` instead of deleting them. This way the public update site url would have stayed as is, without users noticing and forcing them to uninstall/install from the new update site to upgrade.

**Comment by Calixte** [comment]
I'll try to do that for sure. I deleted them because I couldn't find a solution fast enough, and didn't want the old URL to be a source of confusion. 
I also want to bring back the archives that can be manually installed.
And I think it's also missing a reference to the sventu update site.

**Comment by romani** [comment]
We can think on sevntu later on. It has separate update site so users have workaround

**Pull request merged**
