### PR TITLE
fix #375: don't block UI when loading metadata

### LINKED ISSUE #375: creating new config blocks main thread
Creating a new configuration from the preference page leads to blocking the main thread for several seconds. That operation should be run via a UI job to avoid "application not responding".

### PR DESCRIPTION
**Pull request by Bananeweizen**
Use a progress dialog with indeterminate progress while loading the metadata. That way the UI thread is not blocked, and Windows does not show "application not responding". The progress dialog automatically closes after metadata loading has finished.

grafik

### CODE REVIEW

**Review by romani — APPROVED** [review]
I surprised that this is not instant

**Comment by Calixte** [comment]
> I surprised that this is not instant

Me too. It's nearly instantaneous on my machine.

**Comment by Bananeweizen** [comment]
> It's nearly instantaneous on my machine.

That's when it has been loaded by another action (like running scan) before. If you just start Eclipse without any build running, and then go to the configuration, you will see quite a delay (some seconds in my case), but only the first time.

**Comment by rnveach** [comment]
This also shows up in the Error Log view. I assume this fix has not been released yet.

ui freeze

**Pull request merged**
