### PR TITLE
Update to Checkstyle 8.26

### PR DESCRIPTION
**Pull request by ManfredTremmel**
After updating my projects to Checkstyle 8.24, I always get errors in eclipse with the new checkstyle configuration. So I've updated the project myselfe, I hope you can use my changes

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot, please give us a time to review

**Comment by ManfredTremmel** [comment]
No problem, take as long as you need. I've compiled my version and it works as it should for me.

**Comment by Calixte** [comment]
This version has the `tabWidth` offset bug.

Here is a screenshot from 8.18:
good
Here is this version:
not_good

See #167, #158 for possible solutions.

**Comment by ManfredTremmel** [comment]
I've updated to Checkstyle 8.25 and tried to fix the wrong tabWidth detection. Personal I don't use tabs in my project, but I've reconfigured one and I think it looks good:

image

@Calixte please test this version, I hope it solves your problems.

**Comment by ManfredTremmel** [comment]
For discussion: Isn't it the wrong way to read tabWidth from checkstyle configuration? When it's used to place the highlighting in the eclipse editor, wouldn't be the editors tabWidth configuration the correct value? Yes I know in a valid setup both should have the same entry.

**Comment by rnveach** [comment]
> Isn't it the wrong way to read tabWidth from checkstyle configuration? When it's used to place the highlighting in the eclipse editor, wouldn't be the editors tabWidth configuration the correct value? Yes I know in a valid setup both should have the same entry.

I personally don't know how eclipse works but the main thing is that the highlighting needs to work as expected.
If Eclipse and Checkstyle have a different tab setting and using the wrong one in Eclipse skews the text that is highlighted, then there needs to be some conversion between the 2 so the expected text being flagged by Checkstyle is highlighted correctly in Eclipse.

Also as mentioned before, each module in Checkstyle can be configured with a different tab width. You may want text files to have a width of 8 but java files have a width of 4.

**Comment by romani** [comment]
@lkoe , please pay attention to this PR, we need to merge such changes, as all of us need new plugin.
I understand you have no time to maintain project as it was before, please find me in private email to share release process keys to let me release Eclipse-cs after merge, to not be blocked by your free time.

**Comment by ManfredTremmel** [comment]
@Calixte looks like a great improvement, getting rid of calculating the position.

**Comment by romani** [comment]
@ManfredTremmel , sorry for delay, I will switch to eclipse-cs very soon, to unblock your updates.

**Comment by romani** [comment]
@ManfredTremmel , thanks a lot for contribution.
I need to make hard choice what PR to use to proceed yours or #167 .
I am more leaning to #167 , as it allow have version by version update, so it will be very good for users.

Can you review #167 PR and approve it?  if all done properly.
I appreciate your help, It would be awesome if you can become maintainer of plugin to keep it alive.

**Comment by ManfredTremmel** [comment]
@romani let's integrate #167, I'll pull the changes and update my branch to checkstyle version 8.26, then you can take the changes into the repository, if you wan't. It's not so easy to keep in sync with all this new releases and I really hate not having correct checkstyle warning in eclipse because of incompatibility in the configuration  ;-)

**Comment by romani** [comment]
Let's coordinate with @Calixte , as he already has a separate updates for all version but I am not sure about latest.

Sorry that project is such state that some work might already duplicated. I hope after we update to recent version during next month. We will coordinate work to avoid wasting of time.

I right now almost paused my activity in core project to unblock both of you.
I really hope to onboard both of you as maintainers to keep project alive. I can not keep all projects, so your activity is in high demand

**Comment by reckart** [comment]
Hi - I'm trying to locally build this PR to get eclipse-cs working again on my machine, but Maven doesn't compile it on the command line. I have checked out the branch, imported everything into Eclipse and then try to run `mvn clean install` on the command line (these are the build instructions given in the repo) - but the build fails with the message:

```
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: net.sf.eclipsecs:net.sf.eclipsecs.branding:8.26.0-SNAPSHOT @ /Users/bluefire/git/eclipse-cs/net.sf.eclipsecs.branding/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/releases/juno/201303010900/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/juno/201303010900/
[INFO] Adding repository http://download.eclipse.org/releases/juno/201303010900
[INFO] Resolving dependencies of MavenProject: net.sf.eclipsecs:net.sf.eclipsecs.branding:8.26.0-SNAPSHOT @ /Users/bluefire/git/eclipse-cs/net.sf.eclipsecs.branding/pom.xml
[ERROR] Cannot resolve target definition:
[ERROR]   Problems resolving provisioning plan.:
[ERROR]      Unable to satisfy dependency from org.eclipse.sdk.ide 4.2.2.M20130204-1200 to org.eclipse.equinox.p2.iu; config.a.jre.javase [1.6.0,1.6.0].
[ERROR]      Unable to satisfy dependency from org.eclipse.sdk.ide 4.2.2.M20130204-1200 to org.eclipse.equinox.p2.iu; a.jre.javase [1.6.0,1.6.0].
[ERROR]      Unable to satisfy dependency from tycho-ee-1573067109084 0.0.0.1573067109084 to org.eclipse.equinox.p2.iu; a.jre.javase [13.0.0,13.0.0].
[ERROR]
[ERROR] Failed to resolve target definition /Users/bluefire/git/eclipse-cs/net.sf.eclipsecs.target/net.sf.eclipsecs.target.target: See log for details -> [Help 1]
```

Any ideas?

**Comment by romani** [comment]
my environment:
```
mvn --version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T08:06:16-07:00)
Maven home: /opt/maven/apache-maven-3.6.2
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: /opt/jvm/jdk1.8.0_162/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-166-generic", arch: "amd64", family: "unix"
```
and `mvn install` passed.

**Comment by reckart** [comment]
I was trying to use the Oracle Java 13 SDK. Switching back to Java 8 seems to do the trick. Thanks!

**Comment by ManfredTremmel** [comment]
> I was trying to use the Oracle Java 13 SDK. Switching back to Java 8 seems to do the trick. Thanks!

I'm using openJDK 11, this also works. I haven't tried the short time supported versions.

**Comment by romani** [comment]
Alternativedix is merged at https://github.com/checkstyle/eclipse-cs/pull/187

**Pull request closed without merging**
