### PR TITLE
Issue #340: update to Checkstyle 10.0

### LINKED ISSUE #340: upgrade to checkstyle 10.0
https://checkstyle.org/releasenotes.html#Release_10.0

### PR DESCRIPTION
**Pull request by Calixte**
Fixes #340.
Screen Shot 2022-04-19 at 11 04 10 PM

### CODE REVIEW

**Comment by romani** [comment]
Travis.yml need change like https://github.com/checkstyle/checkstyle/blob/b09a9ce9d4f48c179f3d5647b6656e5737462656/.travis.yml#L31

**Comment by romani** [comment]
I updated Travis

**Review by romani — APPROVED** [review]
@Calixte , I fixed Travis, please merge.

**Review by rnveach — COMMENTED** [review]
> BIN +12.8 MB
[...lipsecs.checkstyle/checkstyle-9.3-all.jar → ...ipsecs.checkstyle/checkstyle-10.0-all.jar](https://github.com/checkstyle/eclipse-cs/pull/345/files#diff-4f80eab7c672657816c8dbf8561a19ebaa177a5a8d208377875bf6106a510697)

~Not a stopper from merging, but is it a concern that our JAR increased in size by 12 megs?~
Edit: This just seems to be how github displays it. I thought it would display the difference, but its displaying the full file size. It is the expected size and I am not seeing any concerns when I look at the all jars I have for the previous releases.

**Pull request merged**
