### PR TITLE
Issue #306: update to Checkstyle 8.45

### LINKED ISSUE #306: upgrade to checkstyle 8.45
https://checkstyle.org/releasenotes.html#Release_8.45

### PR DESCRIPTION
**Pull request by Calixte**
Fixes #306.

I had to revert the removal of the reflections library. It will be possible to reapply that change after Checkstyle 9.1.
I also had to revert some of the metadata deletion. The plugin couldn't find the root modules (like Checker).
FYI @rnveach

### CODE REVIEW

**Comment by Calixte** [comment]
There's a problem with the travis tests.
They [failed](https://app.travis-ci.com/github/checkstyle/eclipse-cs/jobs/551132672) but are reported as passing here.

**Comment by romani** [comment]
https://app.travis-ci.com/github/checkstyle/eclipse-cs/jobs/551132672#L2177

**Comment by romani** [comment]
I will fix this , it is due to missed `set -e` at
https://github.com/checkstyle/eclipse-cs/blob/9d3ba763fa614fb4635a7973ef2cdd44f524b0d8/.travis.yml#L52
This block of bash has to moved to separate bash script.

**Comment by romani** [comment]
Surprised that such update https://checkstyle.org/releasenotes.html#Release_8.45 results in problems

**Comment by Calixte** [comment]
It's not because of the update itself, it's because of the changes that were made since the previous update. 
They were probably not fully tested.

**Comment by romani** [comment]
CI fixed at https://github.com/checkstyle/eclipse-cs/commit/07c0c9cc9963fd327b10df788e76b7a017a45720

This PS is rebased over master

**Review by romani — APPROVED** [review]
please share some images or any other prove that plugin is working (can do some violation).
it always helps us to not to release not working plugins.

**Comment by rnveach** [comment]
> FYI @rnveach

I would also like to see what you found that shows my changes are not functioning properly. I did test them out with violations and did not see an issue. So I am curious what I missed.

**Comment by Calixte** [comment]
@romani 
Here is a screenshot with some violations from the NoWhitespaceBeforeCaseDefaultColon check introduced in 8.45:
Screen Shot 2021-12-24 at 1 37 30 PM

@rnveach 
- For the missing metadata of Checker and TreeWalker, you can reproduce by either adding a new check to an existing internal configuration, or by creating a new internal configuration.
Screen Shot 2021-12-24 at 1 41 50 PM
```
net.sf.eclipsecs.core.util.CheckstylePluginException: No root module found.
	at net.sf.eclipsecs.core.config.ConfigurationWriter.write(ConfigurationWriter.java:114)
	at net.sf.eclipsecs.core.config.CheckConfigurationWorkingCopy.setModules(CheckConfigurationWorkingCopy.java:263)
	at net.sf.eclipsecs.ui.config.CheckConfigurationConfigureDialog.okPressed(CheckConfigurationConfigureDialog.java:251)
```
```
java.lang.NullPointerException
	at net.sf.eclipsecs.core.config.savefilter.SuppressWarningsHolderSaveFilter.postProcessConfiguredModules(SuppressWarningsHolderSaveFilter.java:51)
	at net.sf.eclipsecs.core.config.savefilter.SaveFilters.process(SaveFilters.java:90)
	at net.sf.eclipsecs.core.config.ConfigurationWriter.write(ConfigurationWriter.java:89)
	at net.sf.eclipsecs.core.config.ConfigurationWriter.writeNewConfiguration(ConfigurationWriter.java:69)
	at net.sf.eclipsecs.ui.config.configtypes.InternalConfigurationEditor.ensureFileExists(InternalConfigurationEditor.java:243)
	at net.sf.eclipsecs.ui.config.configtypes.InternalConfigurationEditor.getEditedWorkingCopy(InternalConfigurationEditor.java:209)
	at net.sf.eclipsecs.ui.config.CheckConfigurationPropertiesDialog.okPressed(CheckConfigurationPropertiesDialog.java:323)
```

- For the org.reflections library, I get the following exception on startup, which then leads to many bugs in the plugin exception. It is a known bug in version 0.9.12 which comes with Checkstyle 8.45. Eclipse-cs was using 0.9.10 which doesn't have the bug. I will be able to reapply your change once we reach Checkstyle 9.1 which upgrades to a version of org.reflections where this bug is fixed.
https://github.com/ronmamo/reflections/issues/273
```
 org.reflections.ReflectionsException: Scanner ResourcesScanner was not configured
	at org.reflections.Store.get(Store.java:39)
	at org.reflections.Store.get(Store.java:61)
	at org.reflections.Store.get(Store.java:56)
	at org.reflections.Reflections.getResources(Reflections.java:564)
	at org.reflections.Reflections.getResources(Reflections.java:572)
	at com.puppycrawl.tools.checkstyle.meta.XmlMetaReader.readAllModulesIncludingThirdPartyIfAny(XmlMetaReader.java:82)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.createMetadataMap(MetadataFactory.java:582)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.doInitialization(MetadataFactory.java:559)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.refresh(MetadataFactory.java:539)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.<clinit>(MetadataFactory.java:144)
```

**Comment by romani** [comment]
@Calixte , thanks a lot, please merge and proceed with releases

**Pull request merged**
