### PR TITLE
infra: harden GitHub workflows

### PR DESCRIPTION
**Pull request by Bananeweizen**
See https://github.com/step-security/secure-repo#1-automatically-set-minimum-github_token-permissions for details. Dependabot will be able to upgrade the pinned dependencies and will use the same format (including version comments).

### CODE REVIEW

**Comment by rnveach** [comment]
@romani @nrmancuso ping for main repo's GH workflows

**Comment by rnveach** [comment]
@Bananeweizen Just a question, do you know if this has any impact on dependabot updates for GH actions?

I ask because you specify the commits, but when we enabled dependabot for these in our repo, it updated version numbers. Not sure if some other configuration is needed, or if it will work out of the box here.

**Comment by rnveach** [comment]
Nevermind, missed your comment completely.

**Comment by Bananeweizen** [comment]
recreated as #611 instead

**Pull request closed without merging**
