### PR TITLE
Infra: ignore changes to docs directory

### PR DESCRIPTION
**Pull request by Calixte**
See https://github.com/checkstyle/eclipse-cs/pull/532#issuecomment-1615281172

### CODE REVIEW

**Comment by romani** [comment]
May be you need to just ignore spaces in diff?
So you will be notified only when content is changed.

**Comment by Calixte** [comment]
I don't really understand why we have this validation script.
It forces us to commit the documentation changes to the `docs` directory ahead of the release instead of during the release. Sometimes we want to, sometimes not, so I'm not sure why we enforce it.
But anyways, everything is blocked by the Travis CI JDK 17 build that fails without any logs. Do we still need Travis now that we have GitHub CI?

**Comment by romani** [comment]
I do not remember if Travis do something special, if we migrated completely off it, we can disable it.

For git change of this PR, I am to merge if you think there is no value in such git diff.

You can merge PR, even Travis is not happy.

**Comment by romani** [comment]
I restarted Travis

**Comment by rnveach** [comment]
Travis is just trouble and should be removed from all repos.

> if Travis do something special

Travis does JDK 17, but since it isn't working there is no point in keeping it. Just create an issue to restore it after it is removed.

> I don't really understand why we have this validation script.

@Calixte 

See https://github.com/checkstyle/eclipse-cs/pull/474#issue-1571560662

We use `git-diff` in main repo to ensure everything being modified by the script is either committed or removed to show nothing by the user was forgotten.

The little override being fixed here was there initially to basically ignore certain things changing since originally it was just timestamps. It is fine to ignore the whole folder if that is what is expected, the issue will only be at release time to remember to manually commit the folder with the release changes.

**Comment by Calixte** [comment]
> the issue will only be at release time to remember to manually commit the folder with the release changes

The release script will commit any changes: https://github.com/checkstyle/eclipse-cs/blob/master/release.sh#L72

I'm going to make another PR to remove Travis.

**Comment by romani** [comment]
If we ok to remove Travis, please merge this PR now.
State of Travis becomes irrelevant.

**Comment by Bananeweizen** [comment]
Travis has been removed meanwhile, and all JDKs are tested at github, therefore merging.

**Pull request merged**
