### PR TITLE
Multiple source cleanups

### PR DESCRIPTION
**Pull request by Bananeweizen**
I was going to fix some deprecations, but doing so I noticed that the code would get littered with more and more duplicated catch-clauses due to newly introduced exception types in the non deprecated methods. Therefore I converted catch to multi-catch and ran some other cleanups. All changes were done fully automated, except for removing some no longer necessary @SupressWarning statements.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Can someone explain why the build failed? It looks like it checks all changed files for checkstyle violations. If so, the current EclipseCS sources have around 1400 violations, therefore any somewhat bigger change will fail this check.

**Comment by Bananeweizen** [comment]
This needs to be rebased after #351 has been fixed and the resulting checkstyle issues are also fixed.

**Comment by rnveach** [comment]
> Can someone explain why the build failed? 

https://app.travis-ci.com/github/checkstyle/eclipse-cs/jobs/571713439#L456
These changes resulted in `34 errors` by the rules defined in your configuration at https://github.com/checkstyle/eclipse-cs/blob/5b295acc79fd1bc37e38d9a2f06c01667c57ed29/config/checkstyle_checks.xml#L6 .

Checkstyle checks all files and has no "file changed" recognition. I assume the 1400 errors may be from running with a different configuration then eclipse-cs'.

Travis run seems correct to fail this PR as everything passed at the other PR, https://github.com/checkstyle/eclipse-cs/pull/349 .

**Comment by romani** [comment]
on this branch, on my local, with `mvn install` in root folder of repo, I also have no violations.

**Comment by romani** [comment]
@Bananeweizen ,

Patch filter works on last commit changes.
on local history is linear, so patch using your last commit about `infra: re-enable IllegalInstantiation check`
in Travis, all commits are combined as one merge commit that is applied over master HEAD (it is non configurable feature of Travis) to not execute CI on old code and clearly know result after merge.

So Travis is right :).
you suppose to reproduce this problem is you checkout to each commit seprately and run "mvn install" on each of them

**Comment by romani** [comment]
@Bananeweizen , reminder one more time.
if there be situation with **avalanche of demands** from Checkstyle , **please do not follow it**, report it reviewers and we all can agree to merge with red CI. After merge, it might not be problem, if last commit is not touching problematic lines. So violations will stay in backlog and will not bother people until next update.

**Comment by romani** [comment]
@Bananeweizen , can we finish this PR ?

**Comment by romani** [comment]
I merging this PR as we found problem with Windows for patch filter
https://github.com/checkstyle/patch-filters/issues/113
https://github.com/checkstyle/eclipse-cs/pull/395

without such fix, it will be not easy to fix problems in such big update.
We will keep enforcement in next PRs.

**Comment by Bananeweizen** [comment]
Sorry for not coming back to this earlier. I had tried to debug into the patch filter to understand what's going on, but I failed miserably with that. Next time I'll try to clean up open PRs first.

**Pull request merged**
