### PR TITLE
#161 Update to Checkstyle 8.21

### PR DESCRIPTION
**Pull request by Calixte**

### CODE REVIEW

**Comment by rnveach** [comment]
@Calixte I see some files that still have `8.19` which seems odd if we are on 8.20 going to 8.21. I assume they are referencing checkstyle but can you confirm. I just did a search to find these and don't know the project or eclipse layout very well.

https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF#L5
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs-feature/feature.xml#L2
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs-updatesite/category.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.ui/META-INF/MANIFEST.MF#L5
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.checkstyle/.classpath#L3
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.checkstyle/build.properties#L4
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.ui/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.checkstyle/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.core/META-INF/MANIFEST.MF#L5
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs-updatesite/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.doc/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.branding/META-INF/MANIFEST.MF#L5
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.doc/META-INF/MANIFEST.MF#L5
https://github.com/checkstyle/eclipse-cs/blob/master/docs/update/compositeArtifacts.xml#L11
https://github.com/checkstyle/eclipse-cs/blob/master/docs/update/compositeContent.xml#L11
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.branding/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.sample/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.target/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.core/pom.xml#L6
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.sample/META-INF/MANIFEST.MF#L5
https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs-feature/pom.xml#L6

**Comment by Calixte** [comment]
Those are "traditionally" changed in a follow-up commit like this one: fb552f7dadd114047f18b6c124436860e9d18efe
@romani said he would do them when he releases. I can definitely do them if he changes his mind, or for future releases. Just let me know.

**Comment by romani** [comment]
yes, lets keep as is while we catch up latest checkstyle release.
All improvements are welcome after catchup.

thanks a lot , merged manually.

@Calixte , it would awesome if you start to follow rules of commit messages as we have in core project.
You simply need to make it "Issue #161: update to Checkstyle 8.21".

**Comment by rnveach** [comment]
@romani 

> yes, lets keep as is while we catch up latest checkstyle release.

What does this mean for the POMs, especially where we start introducing breaking compatibility? Are we sure the versions we are releasing are even working as intended and somehow it isn't really using an old version.

I especially dont see why the POM versions have to be 1 behind during the update process.

**Comment by romani** [comment]
I have no good answer for you, but it worked for me. I just do some step

**Pull request closed without merging**
