### PR TITLE
Issue #1: update to Checkstyle 8.7

### PR DESCRIPTION
**Pull request by lkoe**
Issue #1: update to Checkstyle 8.7

### CODE REVIEW

**Comment by romani** [comment]
I is hard to review now, what I recommend is to reference issue in commit message and PR description.
And have only one commit.
I recommend eventually come up to our rules for PRs https://github.com/checkstyle/checkstyle/wiki/PR-rules ,let me know if you agree and when you would like to follow.

I also changed settings of project to allow only "rebase and merge" commits as it helps a lot in git history investigations.

**Comment by lkoe** [comment]
Thanks Roman, I was still toying around with the tools. Also my commit user/email was off. Should be better now.

**Comment by romani** [comment]
In future it is better to not mix different changes in one commit.
it is better to have several commits or several issues(PRs), it helps others project maintainers to understand what forced you to make changes like this.

I know that is a bit more complicated(bureaucracy), but as we work together we should share a bit more context of why changes are required.

**Comment by lkoe** [comment]
> In future it is better to not mix different changes in one commit.

agreed :-)

**Pull request merged**
